"""
Language registry -- the single source of truth for which languages exist and
what is turned on for each: ACF fields, nav/footer chrome sync, dropdown
visibility. Backed by one WP option (pilgrim_languages) via a small REST
endpoint registered in functions.php (pilgrim/v1/languages).

Adding a language is one call: save_language(). The native (self-language)
label shown in the dropdown is auto-generated by translating the English
name into itself via Gemini, unless one is passed explicitly.
"""

from __future__ import annotations

import httpx

from app.config import settings
from app.tasks.gemini_translate import translate as gtranslate

_ENDPOINT = "/wp-json/pilgrim/v1/languages"
AUTH = (settings.wp_user, settings.wp_app_password)


def _url() -> str:
    return settings.wp_url.rstrip("/") + _ENDPOINT


def get_languages() -> dict:
    """{ code: {name, native, fields, chrome, visible} } for every known language."""
    r = httpx.get(_url(), auth=AUTH, timeout=30)
    r.raise_for_status()
    return r.json()


def save_language(
    code: str, name: str, *, fields: bool, chrome: bool, visible: bool, native: str | None = None
) -> dict:
    """Add or update a language's entry in the registry."""
    if not native:
        try:
            native = gtranslate(name, "en", code).strip() or name
        except Exception:
            native = name
    r = httpx.post(
        _url(),
        json={"code": code, "name": name, "native": native, "fields": fields, "chrome": chrome, "visible": visible},
        auth=AUTH,
        timeout=30,
    )
    r.raise_for_status()
    return r.json()
